### ISSUE TITLE
Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by NetOpWibby** [florianheinemann/www-passwordless-net#12]
I get this error when running this site locally. I was trying to get passwordless working for me and there's just enough things that don't work that makes this frustrating.

**Comment by florianheinemann** [comment]
You're trying to run www.passwordless.net or passwordless? What steps caused that issue?

**Comment by NetOperatorWibby** [comment]
I'm trying to run both actually.

My app is based on Feathers (but it's effectively Express) and was running into an issue with:

```
userSchema.statics.findUser = (email, done) => {
	email = email.toLowerCase();
	this.findOne({ email: email }, done);
};
```

`findOne` isn't a function, according to my console, and I copied/pasted what is in this repo. Since I didn't find a way around that issue, I decided to run `www-passwordless-net` so I could deconstruct it, and that's when I got this bson error. Same as when I copied/pasted so I don't know what's going on. Installing `bson` via npm didn't work either.

**Comment by florianheinemann** [comment]
It seems to be a problem with mongoose if you don't have Python installed. This might be worth trying: http://stackoverflow.com/a/35516644 

I would probably start with an even simpler example: https://github.com/florianheinemann/passwordless/tree/master/examples/simple-mail

**Comment by NetOperatorWibby** [comment]
I was able to get the simpler example working (had to change the email portion to work with Sendgrid). However, that `bson` issue still occurs.
![screen shot 2016-10-12 at 12 47 04 pm](https://cloud.githubusercontent.com/assets/1288356/19319240/01e8c81e-907a-11e6-8d82-1774b9cc88da.png)

**Comment by NetOperatorWibby** [comment]
I reinstalled Python as well (via `brew install python`).

**Comment by florianheinemann** [comment]
You seem to have added MongoDB to the simple-mail example. The issues are also MongoDB related (as shown in the error messages). I would suggest asking the folks at MongoDB for support. Generelly, I'd probably try to use the latest Mongoose and latest MongoDB version.

**Comment by NetOperatorWibby** [comment]
No, I never added anything mongo-related. I simply ran `npm install`, that's it. [This answer](http://stackoverflow.com/a/34386030/1167646) solved the `bson` issue for me and it isn't optimal for production but whatevs.

For reference, here is my entire `app.js` file:

```
var express = require('express');
var path = require('path');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var expressSession = require('express-session');
var bodyParser = require('body-parser');

var helper = require("sendgrid").mail;
var sg = require("sendgrid")("SENDGRID API KEY");

var passwordless = require('passwordless');
var MongoStore = require('passwordless-mongostore');

var routes = require('./routes/index');
var app = express();

// TODO: MongoDB setup (given default can be used)
var pathToMongoDb = 'mongodb://localhost/passwordless-simple-mail';

// Setup of Passwordless
passwordless.init(new MongoStore(pathToMongoDb));

passwordless.addDelivery(
    function(tokenToSend, uidToSend, recipient, callback) {

      var
        domain = "http://localhost:3000",
        host = "CoolProject",
        from_email = new helper.Email("hello@cool.project"),
        to_email = new helper.Email(recipient),
        subject = "Sign into your account!",
        content = new helper.Content("text/plain", "Hello!\nAccess your " + host + " account here: " + domain + "/account?token=" + tokenToSend + "&uid=" + encodeURIComponent(uidToSend)),
        mail = new helper.Mail(from_email, subject, to_email, content),
        request = sg.emptyRequest({
          method: "POST",
          path: "/v3/mail/send",
          body: mail.toJSON(),
        });

      sg.API(request, function (error, response) {
        if (error) {
          console.log(error);
        }

        callback(error);
      });
    });

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// Standard express setup
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(cookieParser());
app.use(expressSession({secret: '42', saveUninitialized: false, resave: false}));
app.use(express.static(path.join(__dirname, 'public')));

// Passwordless middleware
app.use(passwordless.sessionSupport());
app.use(passwordless.acceptToken({ successRedirect: '/' }));

// CHECK /routes/index.js to better understand which routes are needed at a minimum
app.use('/', routes);

/// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// development error handler
app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: err
    });
});

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + server.address().port);
});
```

**Comment by florianheinemann** [comment]
MongoDB is still used in your code:
`var MongoStore = require('passwordless-mongostore');`

You even init it:
`passwordless.init(new MongoStore(pathToMongoDb));` 

If you want to get rid of MongoDB use something like: https://github.com/andreafalzetti/passwordless-nodecache It uses no database but simply stores all data in memory

**Comment by NetOperatorWibby** [comment]
> You seem to have added MongoDB to the simple-mail example.

https://github.com/florianheinemann/passwordless/blob/master/examples/simple-mail/app.js#L11

I was saying that I did *not* add it, it was already there.

**Comment by NetOperatorWibby** [comment]
You sent me a link to a simpler example and then said I added the very module that's causing issues. This is where my confusion stems from. I don't have a problem with MongoDB, I was just trying to fix an issue that popped up.

**Comment by florianheinemann** [comment]
Right - sorry, didn't realize it was still in there. I should have switched the example to an in-memory solution to make it even simpler. Anyhow, it boils down to an updated MongoDB version.

I've just updated the example to pull the latest MongoStore which in turn has a more recent MongoDB adapter.

**Comment by NetOperatorWibby** [comment]
That fixed the issue. I'll do the same in my FeathersJS project as well, thanks for tracking down the solution.
